name: Robot Framework Automation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # Configura o Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.14.0-beta.1

      # Instala as dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-browser
          pip install playwright
          playwright install

      # Executa os testes do Robot Framework
      - name: Executar testes
        run: |
          robot -d ./results Robot/Teste/Autom.robot
