name: Robot Framework Automation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y wget unzip xvfb curl libxi6 libg
